<a href="https://colab.research.google.com/github/Priyanshi1704/Machine-LearningLab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Part1: Numpy basics

In [37]:
#Write a NumPy program to create an array of 10 zeros,10 ones,10 fives

import numpy as np
arr0=np.zeros(10,int)
print(arr0)
arr1=np.ones(10,int)
print(arr1)
arr2=(arr1)*5
print(arr2)
arr=np.concatenate((arr0,arr1,arr2))
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


In [23]:
#Write a NumPy program to create an array of all the even integers from 10 to 50

import numpy as np
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [29]:
#Write a NumPy program to generate a random number between 0 and 1

import numpy as np
num=np.random.rand(1)
print(num)

[0.27842467]


In [36]:
#Write a NumPy program to save the matrix (generated in question 3) to a text file and load it
import numpy as np
arr=np.random.rand(6).reshape(2,3)
print(arr)

np.savetxt("file.txt", arr)
content = np.loadtxt('file.txt')
print("\nContent in file.txt:\n", content)


[[0.16612916 0.35501735 0.42773174]
 [0.34928783 0.15626378 0.60070437]]

Content in file.txt:
 [[0.16612916 0.35501735 0.42773174]
 [0.34928783 0.15626378 0.60070437]]


# Part 2: Pandas Excel

In [47]:
#Write a python program to read an image and save the image as a matrix to a .csv file using pandas

# Import required libraries
import numpy as np
import matplotlib.image as img
import pandas as pd

# Read an image
imageMat = img.imread('input.jpg')
print("Current image shape:",imageMat.shape)


Current image shape: (1203, 975, 3)


In [56]:
if (imageMat.shape[2] == 3): # If image is colored i.e the RGB Image then reshape it from 3D matrice to 2D matrice.
  imageMat_reshape = imageMat.reshape(imageMat.shape[0],-2)
  print("Reshaping the 3D array to a 2D array:", imageMat_reshape.shape)

else: # If image is grayscale remain as it is
  imageMat_reshape = imageMat

mat_df = pd.DataFrame(imageMat_reshape) # converting the image matrix to a dataframe using the pandas library imported as pd 

mat_df.to_csv('output.csv', header = None, index = None) # Exporting the dataframe to a CSV file.

Reshaping the 3D array to a 2D array: (1203, 2925)


In [50]:
#Write a program to import excel data from the .csv file (generated in question 1) by excluding the last row and last column

try:
  df = pd.read_csv('output.csv', sep = ',', header = None) # retrieving dataframe from CSV file
  # Getting matrice values.
  print("Before dataframe shape: ",df.shape)
  df.drop(df.tail(1).index,inplace=True) # drop the last 1 rows
  df.drop(columns=df.columns[-1:], axis=1,inplace=True) #  drop the last column
  
  print("After dataframe shape: ",df.shape)

except FileNotFoundError:
  print('output.csv File not found! Try Again')

except Exception: # If any other error occurs, print the file name
  print('Another Error occured!! Try Again')



Before dataframe shape:  (1203, 2925)
After dataframe shape:  (1202, 2924)


In [51]:
#Write a Pandas program to create the today's date

import pandas as pd
from datetime import datetime
now = pd.to_datetime(str(datetime.now()), format='%Y-%m-%d')
print("Today's date: in <Year><month><date> <hour><min><sec><ns> format")
print(now)

Today's date: in <Year><month><date> <hour><min><sec><ns> format
2021-08-09 06:00:49.399458



Part-3
. **Create a mini calculator to know the age of a person after putting the range (i.e. date of birth and current date)**

In [55]:
from datetime import date

def calculateAge(birthDate):
  days_in_year = 365.2425
  total_days = (date.today() - birthDate).days
  age = int((date.today() - birthDate).days / days_in_year)
  months = total_days - age*days_in_year
  months = months//30
  days = total_days - months*30 - age*days_in_year
  return age, months, days

# Driver code
print(calculateAge(date(2001, 4, 17)), "years")
print(calculateAge(date(1997, 2, 3)), "years")

while True:
  try:
    day = int(input("Please enter date of birthday: "))
    break
  except ValueError:
    print("Error! Try Again:")
    day = int(input("Please enter  date of birthday: "))
    break
while True:
  try:
    month = int(input("Please enter your birth month"))
    break
  except ValueError:
    print("Error! Try Again:")
    month = int(input("Please enter your birth month"))
    break
while True:
  try:
    year = int(input("Please enter your birth year"))
    break
  except:
    print("Error! Try Again:")
    year = int(input("Please enter your birth year"))
    break
year, months, days = calculateAge(date(year*1, month*1, day*1))
print("You are",year,"years,", abs(int(months*1)),"months","and",abs(int(days*1)) ,"days old.")

(20, 3.0, 24.149999999999636) years
(24, 6.0, 7.180000000000291) years
Please enter date of birthday: 17
Please enter your birth month04
Please enter your birth year2002
You are 19 years, 3 months and 24 days old.
